import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import { AppLayout } from "@/components/AppLayout/AppLayout";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/lib/theme";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import "./globals.scss";
import { Cursor } from "@/components/Cursor/Cursor";
import BackgroundAnimation from "@/components/BackgroundAnimation/BackgroundAnimation";

const sourceCodePro = Source_Code_Pro({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.className}`}>
        <Cursor />

        <AppRouterCacheProvider>
          <BackgroundAnimation />
          {/* <Background /> */}

          <ThemeProvider theme={theme}>
            <AppLayout>
              {children}

            </AppLayout>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
